# Site settings
title: Monkey Server
email: eduardo@monkey.io
url: http://monkey-project.com
description: "Monkey is a fast and scalable Open Source web server"
skills: "HTTP, Linux"
highlighter: pygments
mk_version: 1.6.7
mk_date: December 31, 2015
mk_major: 1.6

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: C57407
  primary-rgb: "197,116,342"
  secondary: 1D262F
  secondary-dark: 191F26

# Footer settings
footer:
  copyright: Monkey Software
  location: Location
  social: Follow us!
  credits: License

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: slack
    url: http://slack.monkey-project.com
  - title: twitter
    url: http://twitter.com/monkeywebserver
  - title: linkedin
    url: https://www.linkedin.com/grp/home?gid=3211216
  - title: github
    url: http://github.com/monkey/monkey
  - title: rss
    url: http://blog.monkey-project.com/rss/
  - title: google-plus
    url: https://plus.google.com/communities/109231235096868947735

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
